# Generated by Django 4.1.1 on 2022-10-08 04:05

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=200)),
                ('artStyle_image', models.ImageField(upload_to='artstyle_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])])),
                ('is_famous', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=50, null=True)),
                ('art_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork_name', models.CharField(default=None, help_text='Enter a artwork name', max_length=200)),
                ('ordinary_image', models.ImageField(upload_to='temp', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])])),
                ('artwork_image', models.ImageField(upload_to='temp_image_upload_1/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])])),
            ],
        ),
        migrations.CreateModel(
            name='ImageUploadModel_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork_name', models.CharField(default=None, help_text='Enter a artwork name', max_length=200)),
                ('ordinary_image', models.ImageField(upload_to='temp_image_upload_2/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=20)),
                ('occupation', models.CharField(choices=[('Artist', 'Artist'), ('Student', 'Student'), ('Teacher', 'Teacher')], default='Artist', max_length=20)),
                ('avatar_link', models.URLField(default='https://avatars.dicebear.com/api/adventurer-neutral/lifecouldbeadream.svg?r=50')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_image', models.ImageField(upload_to='temp_image_upload/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])])),
            ],
        ),
        migrations.CreateModel(
            name='ArtWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('artwork_image', models.ImageField(upload_to='artwork_images/')),
                ('post_date', models.DateField(default=datetime.date.today)),
                ('artstyle_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artnet_app.artstyle')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='collected_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
        migrations.CreateModel(
            name='ArtComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Enter comment about the art here.', max_length=1000)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artnet_app.artwork')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['post_date'],
            },
        ),
    ]
