# Generated by Django 4.1 on 2023-02-05 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("artnet_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackEnd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("back_end_url", models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="TextPromptModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        default=None,
                        help_text="Enter a what you want to draw.",
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneratedArtwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        help_text="Enter Your Artwork Prompt here.", max_length=500
                    ),
                ),
                ("artwork_image", models.ImageField(upload_to="artwork_images/")),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
